name: Build and Push ex2

# Cand se fac push-uri pe main sau master
on:
  push:
    branches:
      - main
      - master
  
jobs:
# job-ul de build
  build:
    runs-on: ubuntu-latest

    steps:
      # primul pas: checkout
      - name: Checkout
        uses: actions/checkout@v2

      # login in docker hub
      - name: Log in
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build-ul imaginii
      - name: Build
        run: docker build -t gabrielamv1/test-devops-ex2:latest ./ex2/python-app/

      # push pe docker hub
      - name: Push
        run: docker push gabrielamv1/test-devops-ex2:latest